### ISSUE TITLE
improve error reporting

### ISSUE THREAD

**Issue by jonsterling** [alephcloud/hs-aws-kinesis-client#14]
Currently, errors writing to Kinesis are just written to `stdout`. This is clearly not ideal...

**Comment by larskuhtz** [comment]
I think writing to `stderr` would be simple improvement. It may be even the best we could get for a failure in the logging system itself. On a properly setup system messages from stderr might end up in syslog and may make it into some monitoring report.

**Comment by jonsterling** [comment]
Yeah, I think you are right. The immediate improvement is to at least write to `stderr`...
