### ISSUE TITLE
[CLI] Consider using configuration-tools

### ISSUE THREAD

**Issue by jonsterling** [alephcloud/hs-aws-kinesis-client#9]
As much as I treasure the simplicity of the non-`configuration-tools` approach, I think that the various features which come for free from `configuration-tools` could be a big win for usability here.
1. Support for configuration files (even remote ones too, it seems?)
2. An approach to configuring utilities which is uniform across our services

**Comment by larskuhtz** [comment]
I think that, once you learn the pattern, configuration-tools _is_ simple. But it adds boilerplate code, unfortunately _a lot_ of boilerplate code. So maybe it's too simple, in not providing a more sophisticate machinery for generating the boilerplate...

Let me know if I can provide help with this issue.
